package Interfaz;

import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class Inicio extends javax.swing.JFrame {
    private String nombreUsuario="";
    
    public Inicio() {
        initComponents();
        //Imagen de inicio
        InputStream re = this.getClass().getResourceAsStream("/Imagenes/inicio.png");
        Image imagen;
        try {
            imagen = ImageIO.read(re);
            labelInicio.setIcon(new ImageIcon(imagen));
        } catch (IOException ex) {
            Logger.getLogger(InicioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //Constructor que recibe el nombre del usuario logueado
    public Inicio(String nombreUsuario) {
        initComponents();
        this.nombreUsuario = nombreUsuario;
        //Imagen de inicio
        InputStream re = this.getClass().getResourceAsStream("/Imagenes/inicio.png");
        Image imagen;
        try {
            imagen = ImageIO.read(re);
            labelInicio.setIcon(new ImageIcon(imagen));
        } catch (IOException ex) {
            Logger.getLogger(InicioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVer = new javax.swing.JMenu();
        btnCatalogoProductos = new javax.swing.JMenuItem();
        btnRegistroVentas = new javax.swing.JMenuItem();
        btnProductos = new javax.swing.JMenu();
        menuABMProductos = new javax.swing.JMenuItem();
        menuPedidos = new javax.swing.JMenuItem();
        btnClientes = new javax.swing.JMenu();
        menuABMClientes = new javax.swing.JMenuItem();
        btnProveedores = new javax.swing.JMenu();
        menuABMProveedores = new javax.swing.JMenuItem();
        btnVenta = new javax.swing.JMenu();
        menuNuevaVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda de ropa");
        setResizable(false);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        btnVer.setText("Ver");

        btnCatalogoProductos.setText("Catalogo de productos");
        btnCatalogoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoProductosActionPerformed(evt);
            }
        });
        btnVer.add(btnCatalogoProductos);

        btnRegistroVentas.setText("Registro de ventas");
        btnRegistroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroVentasActionPerformed(evt);
            }
        });
        btnVer.add(btnRegistroVentas);

        jMenuBar1.add(btnVer);

        btnProductos.setText("Productos");

        menuABMProductos.setText("ABM Productos");
        menuABMProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuABMProductosActionPerformed(evt);
            }
        });
        btnProductos.add(menuABMProductos);

        menuPedidos.setText("Realizar pedido");
        menuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosActionPerformed(evt);
            }
        });
        btnProductos.add(menuPedidos);

        jMenuBar1.add(btnProductos);

        btnClientes.setText("Clientes");

        menuABMClientes.setText("ABM Clientes");
        menuABMClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuABMClientesActionPerformed(evt);
            }
        });
        btnClientes.add(menuABMClientes);

        jMenuBar1.add(btnClientes);

        btnProveedores.setText("Proveedores");

        menuABMProveedores.setText("ABM Proveedores");
        menuABMProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuABMProveedoresActionPerformed(evt);
            }
        });
        btnProveedores.add(menuABMProveedores);

        jMenuBar1.add(btnProveedores);

        btnVenta.setText("Ventas");

        menuNuevaVenta.setText("Nueva venta");
        menuNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevaVentaActionPerformed(evt);
            }
        });
        btnVenta.add(menuNuevaVenta);

        jMenuBar1.add(btnVenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Abre la ventana ABM Clientes
    private void menuABMClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuABMClientesActionPerformed
        VentanaABMClientes.obtenerVentanaClientes().setVisible(true);
    }//GEN-LAST:event_menuABMClientesActionPerformed

    //Abre la ventana ABM Productos
    private void menuABMProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuABMProductosActionPerformed
        VentanaABMProductos.obtenerVentanaProducto().setVisible(true);
    }//GEN-LAST:event_menuABMProductosActionPerformed

    //Abre la ventana ABM Proveedores
    private void menuABMProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuABMProveedoresActionPerformed
        VentanaABMProveedores.obtenerVentanaProveedores().setVisible(true);
    }//GEN-LAST:event_menuABMProveedoresActionPerformed

    //Abre la ventana Pedidos
    private void menuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosActionPerformed
        VentanaPedidos.obtenerVentanaPedidos().setVisible(true);
    }//GEN-LAST:event_menuPedidosActionPerformed

    //Abre la ventana Ventas
    private void menuNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevaVentaActionPerformed
        VentanaVentas.obtenerVentanaVentas(nombreUsuario).setVisible(true);
    }//GEN-LAST:event_menuNuevaVentaActionPerformed

    //Abre la ventana de registro de ventas
    private void btnRegistroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroVentasActionPerformed
        VentanaRegistroDeVentas.obtenerVentanaRegistroDeVentas().setVisible(true);
    }//GEN-LAST:event_btnRegistroVentasActionPerformed

    //Abre la ventana de catalogo de productos
    private void btnCatalogoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoProductosActionPerformed
        VentanaCatalogoDeProductos.obtenerVentanaCatalogoProductos().setVisible(true);
    }//GEN-LAST:event_btnCatalogoProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCatalogoProductos;
    private javax.swing.JMenu btnClientes;
    private javax.swing.JMenu btnProductos;
    private javax.swing.JMenu btnProveedores;
    private javax.swing.JMenuItem btnRegistroVentas;
    private javax.swing.JMenu btnVenta;
    private javax.swing.JMenu btnVer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JMenuItem menuABMClientes;
    private javax.swing.JMenuItem menuABMProductos;
    private javax.swing.JMenuItem menuABMProveedores;
    private javax.swing.JMenuItem menuNuevaVenta;
    private javax.swing.JMenuItem menuPedidos;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
