package Interfaz;

import Datos.OperacionesBaseDeDatos;
import Operaciones.*;
import Entidades.Producto;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaABMProductos extends javax.swing.JFrame {

    //Usados para llamar a los metodos de dichas clases
    OperacionesBaseDeDatos opBdd = new OperacionesBaseDeDatos();
    OperacionesInterfaz opInterfaz = new OperacionesInterfaz();
    OperacionesClases opClases = new OperacionesClases();
    ValidacionesClases validacionClase = new ValidacionesClases();
    
    //Variable usada para abrir la ventana
    private static VentanaABMProductos ventana=null;
    
    public VentanaABMProductos() {
        initComponents();
        //Evita que se cierre el programa cuando se cierra la ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  
        //Evita que se pueda ingresar o cambiar la id en el textfield
        txtID.setEnabled(false);
    }
       
    //Metodo usado para abrir la ventana. Evita que se abran multiples ventanas del mismo tipo
    public static VentanaABMProductos obtenerVentanaProducto(){
        if (ventana==null) {
            ventana = new VentanaABMProductos();
        }
        return ventana;
    }
    
    //Vacia los textfield en la pestaña Modificar/Baja
    public void vaciarModificar(){
        txtID.setText("");
        txtModificarNombre.setText("");
        txtModificarCodigo.setText("");
        txtModificarDescripcion.setText("");
        txtModificarPrecio.setText("");
        txtStockMinimoModificar.setText("");
        comboModificarTalle.removeAllItems();
    }
    
    //Vacia los textfield en la pestaña Nuevo
    public void vaciarNuevo(){
        txtNuevoNombre.setText("");
        txtNuevoCodigo.setText("");
        txtNuevaDescripcion.setText("");
        txtNuevoPrecio.setText("");
        txtStockMinimo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuProductos = new javax.swing.JTabbedPane();
        panelNuevoProducto = new javax.swing.JPanel();
        labelCategoria = new javax.swing.JLabel();
        txtNuevoPrecio = new javax.swing.JTextField();
        labelNuevaDescripcion = new javax.swing.JLabel();
        btnGuardarProductoNuevo = new javax.swing.JButton();
        labelNuevoTalle = new javax.swing.JLabel();
        labelNuevoPrecio = new javax.swing.JLabel();
        txtNuevoCodigo = new javax.swing.JTextField();
        txtNuevoNombre = new javax.swing.JTextField();
        txtNuevaDescripcion = new javax.swing.JTextField();
        comboNuevaCategoriaProducto = new javax.swing.JComboBox<>();
        labelNuevoCodigo = new javax.swing.JLabel();
        comboNuevoTalle = new javax.swing.JComboBox<>();
        labelNuevoNombre = new javax.swing.JLabel();
        btnVaciarNuevo = new javax.swing.JButton();
        labelNuevoProveedor = new javax.swing.JLabel();
        comboNuevoProveedor = new javax.swing.JComboBox<>();
        btnCargarProveedores = new javax.swing.JButton();
        labelStockMinimo = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        panelModificarProducto = new javax.swing.JPanel();
        txtModificarNombre = new javax.swing.JTextField();
        labelModificarCategoria = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaBuscarProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        txtModificarCodigo = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        labelDescripcionModificar = new javax.swing.JLabel();
        btnGuardarProductoModificado = new javax.swing.JButton();
        labelModificarPrecio = new javax.swing.JLabel();
        labelModificarTalle = new javax.swing.JLabel();
        txtModificarDescripcion = new javax.swing.JTextField();
        btnModificarProducto = new javax.swing.JButton();
        labelModificarNombre = new javax.swing.JLabel();
        comboBuscarProducto = new javax.swing.JComboBox<>();
        txtModificarPrecio = new javax.swing.JTextField();
        labelModificarCodigo = new javax.swing.JLabel();
        comboModificarTalle = new javax.swing.JComboBox<>();
        labelModificarEstado = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        comboModificarCategoriaProducto = new javax.swing.JComboBox<>();
        labelID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnVaciarModificacion = new javax.swing.JButton();
        labelModificarProveedor = new javax.swing.JLabel();
        comboModificarProveedor = new javax.swing.JComboBox<>();
        txtStockMinimoModificar = new javax.swing.JTextField();
        labelStockMinimoModificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Productos");
        setResizable(false);

        labelCategoria.setText("Categoria");

        labelNuevaDescripcion.setText("Descripción");

        btnGuardarProductoNuevo.setText("Guardar");
        btnGuardarProductoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoNuevoActionPerformed(evt);
            }
        });

        labelNuevoTalle.setText("Talle/Talla");

        labelNuevoPrecio.setText("Precio");

        comboNuevaCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa Parte Superior", "Ropa Parte Inferior", "Ropa Interior", "Calzado", "Accesorios" }));
        comboNuevaCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNuevaCategoriaProductoActionPerformed(evt);
            }
        });

        labelNuevoCodigo.setText("Código");

        comboNuevoTalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL" }));

        labelNuevoNombre.setText("Nombre");

        btnVaciarNuevo.setText("Vaciar campos");
        btnVaciarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarNuevoActionPerformed(evt);
            }
        });

        labelNuevoProveedor.setText("Proveedor");

        btnCargarProveedores.setText("Cargar proveedores");
        btnCargarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProveedoresActionPerformed(evt);
            }
        });

        labelStockMinimo.setText("Stock minimo");

        javax.swing.GroupLayout panelNuevoProductoLayout = new javax.swing.GroupLayout(panelNuevoProducto);
        panelNuevoProducto.setLayout(panelNuevoProductoLayout);
        panelNuevoProductoLayout.setHorizontalGroup(
            panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelNuevoProductoLayout.createSequentialGroup()
                        .addComponent(labelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboNuevaCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelNuevoProductoLayout.createSequentialGroup()
                        .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoProductoLayout.createSequentialGroup()
                                .addComponent(labelNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(txtNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                                .addComponent(labelNuevoPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoProductoLayout.createSequentialGroup()
                                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelStockMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNuevaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNuevaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(txtStockMinimo))))
                        .addGap(70, 70, 70)
                        .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(labelNuevoTalle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNuevoTalle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNuevoProveedor))
                                .addGap(18, 18, 18)
                                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                                        .addComponent(comboNuevoProveedor, 0, 141, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCargarProveedores))))))
                    .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVaciarNuevo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarProductoNuevo)
                .addGap(21, 21, 21))
        );
        panelNuevoProductoLayout.setVerticalGroup(
            panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoProductoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNuevaCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCategoria))
                .addGap(47, 47, 47)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoNombre)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevaDescripcion)
                    .addComponent(txtNuevaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoProveedor)
                    .addComponent(comboNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarProveedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoPrecio)
                    .addComponent(labelNuevoTalle)
                    .addComponent(comboNuevoTalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStockMinimo)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProductoNuevo)
                    .addComponent(btnVaciarNuevo))
                .addGap(25, 25, 25))
        );

        menuProductos.addTab("Nuevo", panelNuevoProducto);

        labelModificarCategoria.setText("Categoría");

        tablaBuscarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nombre", "Categoría", "Descripción", "Talle", "Precio", "Stock", "Estado", "Proveedor", "Stock minimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaBuscarProductos);
        if (tablaBuscarProductos.getColumnModel().getColumnCount() > 0) {
            tablaBuscarProductos.getColumnModel().getColumn(0).setMaxWidth(35);
            tablaBuscarProductos.getColumnModel().getColumn(1).setMaxWidth(70);
            tablaBuscarProductos.getColumnModel().getColumn(5).setMaxWidth(40);
            tablaBuscarProductos.getColumnModel().getColumn(6).setMaxWidth(55);
            tablaBuscarProductos.getColumnModel().getColumn(7).setMaxWidth(40);
        }

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        labelDescripcionModificar.setText("Descripción");

        btnGuardarProductoModificado.setText("Guardar");
        btnGuardarProductoModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoModificadoActionPerformed(evt);
            }
        });

        labelModificarPrecio.setText("Precio");

        labelModificarTalle.setText("Talle");

        btnModificarProducto.setText("Modificar");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        labelModificarNombre.setText("Nombre");

        comboBuscarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre" }));

        labelModificarCodigo.setText("Código");

        labelModificarEstado.setText("Estado");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Deshabilitado" }));

        comboModificarCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa Parte Superior", "Ropa Parte Inferior", "Ropa Interior", "Calzado", "Accesorios" }));
        comboModificarCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModificarCategoriaProductoActionPerformed(evt);
            }
        });

        labelID.setText("ID");

        btnVaciarModificacion.setText("Vaciar campos");
        btnVaciarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarModificacionActionPerformed(evt);
            }
        });

        labelModificarProveedor.setText("Proveedor");

        labelStockMinimoModificar.setText("Stock minimo");

        javax.swing.GroupLayout panelModificarProductoLayout = new javax.swing.GroupLayout(panelModificarProducto);
        panelModificarProducto.setLayout(panelModificarProductoLayout);
        panelModificarProductoLayout.setHorizontalGroup(
            panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(panelModificarProductoLayout.createSequentialGroup()
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                .addComponent(labelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelModificarCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelModificarTalle))
                                .addGap(15, 15, 15)
                                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboModificarCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboModificarTalle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDescripcionModificar)
                            .addComponent(labelModificarCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelModificarProveedor, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVaciarModificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardarProductoModificado)
                                .addGap(12, 12, 12))
                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                                .addComponent(txtModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelModificarPrecio))
                                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                                .addComponent(txtModificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelModificarEstado)))
                                        .addGap(38, 38, 38)
                                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                        .addComponent(comboModificarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelStockMinimoModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtStockMinimoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 69, Short.MAX_VALUE))))
                    .addGroup(panelModificarProductoLayout.createSequentialGroup()
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarProducto)
                            .addGroup(panelModificarProductoLayout.createSequentialGroup()
                                .addComponent(comboBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarProducto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelModificarProductoLayout.setVerticalGroup(
            panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto)
                    .addComponent(comboBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificarProducto)
                .addGap(18, 18, 18)
                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarProductoModificado)
                            .addComponent(btnVaciarModificacion))
                        .addGap(60, 60, 60))
                    .addGroup(panelModificarProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelModificarCodigo)
                            .addComponent(txtModificarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelModificarEstado)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelModificarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDescripcionModificar)
                            .addComponent(comboModificarCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelModificarPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelModificarTalle)
                                .addComponent(comboModificarTalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtStockMinimoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelStockMinimoModificar)
                                .addComponent(comboModificarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelModificarProveedor)))
                        .addGap(113, 113, 113))))
        );

        menuProductos.addTab("Modificar / Baja", panelModificarProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuProductos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Boton que carga los campos textfield con los datos del producto seleccionado en la tabla
    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        if (tablaBuscarProductos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono ningún producto", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            opInterfaz.llenarComboProveedores(opBdd.obtenerProveedores(), comboModificarProveedor);
            opInterfaz.llenarCamposProducto(tablaBuscarProductos, txtID, txtModificarCodigo, txtModificarNombre,
                    comboModificarCategoriaProducto, txtModificarDescripcion, comboModificarTalle, txtModificarPrecio, comboEstado, comboModificarProveedor, txtStockMinimoModificar);
        }
        
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    //Boton que guarda el producto modificado en la base de datos
    private void btnGuardarProductoModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoModificadoActionPerformed
        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String talle="";
            if (comboModificarTalle.getItemCount()!=0) {
                talle=comboModificarTalle.getSelectedItem().toString();
            }
            Producto producto = opClases.crearProducto(txtModificarNombre.getText(), txtModificarCodigo.getText(), comboModificarCategoriaProducto.getSelectedItem().toString(),
                    txtModificarDescripcion.getText(), talle, txtModificarPrecio.getText(), comboModificarProveedor.getSelectedItem().toString(), txtStockMinimoModificar.getText());  
            if (validacionClase.ValidarProducto(producto)) {
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Actualizar producto?", "Confirmar", JOptionPane.YES_NO_OPTION); 
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (opBdd.guardarProductoModificado(producto, comboModificarCategoriaProducto.getSelectedItem().toString(), comboEstado.getSelectedItem().toString(), txtID.getText())) {
                        JOptionPane.showMessageDialog(null, "El codigo de producto ya existe. Seleccione otro.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Datos actualizados");
                        vaciarModificar();
                    }
                } 
            }
        }
    }//GEN-LAST:event_btnGuardarProductoModificadoActionPerformed

    //Boton que busca los productos en la base de datos que cumplan con los terminos
    //de busqueda y los agrega a la tabla de productos
    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        opInterfaz.llenarTabla(opBdd.buscarProducto(txtBuscarProducto.getText(),
                comboBuscarProducto.getSelectedItem().toString().toLowerCase()), tablaBuscarProductos);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    //Agrega items al combobox de los talles dependiendo de la categoria de producto seleccionada
    private void comboNuevaCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNuevaCategoriaProductoActionPerformed
        opInterfaz.llenarComboTalle(comboNuevoTalle, comboNuevaCategoriaProducto.getSelectedItem().toString());
    }//GEN-LAST:event_comboNuevaCategoriaProductoActionPerformed

    //Boton que guarda el producto nuevo en la base de datos
    private void btnGuardarProductoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoNuevoActionPerformed
        if (txtNuevoNombre.getText().equals("") || txtNuevoCodigo.getText().equals("")
                || txtNuevaDescripcion.getText().equals("") || txtNuevoPrecio.getText().equals("") || comboNuevoProveedor.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String talle="";
            if (comboNuevoTalle.getItemCount()!=0) {
                talle=comboNuevoTalle.getSelectedItem().toString();
            }
            Producto producto = opClases.crearProducto(txtNuevoNombre.getText(), txtNuevoCodigo.getText(), comboNuevaCategoriaProducto.getSelectedItem().toString(),
                    txtNuevaDescripcion.getText(), talle, txtNuevoPrecio.getText(), comboNuevoProveedor.getSelectedItem().toString(), txtStockMinimo.getText());  
            if (validacionClase.ValidarProducto(producto)) {
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Guardar producto?", "Confirmar", JOptionPane.YES_NO_OPTION); 
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (opBdd.guardarProductoNuevo(producto, comboNuevaCategoriaProducto.getSelectedItem().toString())) {
                        JOptionPane.showMessageDialog(null, "El codigo de producto ya existe. Seleccione otro.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Datos guardados");
                        vaciarNuevo();
                    }
                } 
            }
        }
    }//GEN-LAST:event_btnGuardarProductoNuevoActionPerformed

    //Agrega items al combobox de los talles dependiendo de la categoria de producto seleccionada
    private void comboModificarCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModificarCategoriaProductoActionPerformed
        opInterfaz.llenarComboTalle(comboModificarTalle, comboModificarCategoriaProducto.getSelectedItem().toString());
    }//GEN-LAST:event_comboModificarCategoriaProductoActionPerformed

    //Boton que vacia los campos de los textfield en la pestaña Modificar/Baja
    private void btnVaciarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarModificacionActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea vaciar los campos?", "Confirmar", JOptionPane.YES_NO_OPTION); 
        if (eleccion == JOptionPane.YES_OPTION) {
            vaciarModificar();
        } 
    }//GEN-LAST:event_btnVaciarModificacionActionPerformed

    //Boton que vacia los campos de los textfield en la pestaña Nuevo
    private void btnVaciarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarNuevoActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea vaciar los campos?", "Confirmar", JOptionPane.YES_NO_OPTION); 
        if (eleccion == JOptionPane.YES_OPTION) {
            vaciarNuevo();
        } 
    }//GEN-LAST:event_btnVaciarNuevoActionPerformed

    //Agrega los proveedores al comboBox de la pestaña Nuevo
    private void btnCargarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProveedoresActionPerformed
        opInterfaz.llenarComboProveedores(opBdd.obtenerProveedores(), comboNuevoProveedor);
    }//GEN-LAST:event_btnCargarProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaABMProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaABMProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCargarProveedores;
    private javax.swing.JButton btnGuardarProductoModificado;
    private javax.swing.JButton btnGuardarProductoNuevo;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnVaciarModificacion;
    private javax.swing.JButton btnVaciarNuevo;
    private javax.swing.JComboBox<String> comboBuscarProducto;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboModificarCategoriaProducto;
    private javax.swing.JComboBox<String> comboModificarProveedor;
    private javax.swing.JComboBox<String> comboModificarTalle;
    private javax.swing.JComboBox<String> comboNuevaCategoriaProducto;
    private javax.swing.JComboBox<String> comboNuevoProveedor;
    private javax.swing.JComboBox<String> comboNuevoTalle;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcionModificar;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelModificarCategoria;
    private javax.swing.JLabel labelModificarCodigo;
    private javax.swing.JLabel labelModificarEstado;
    private javax.swing.JLabel labelModificarNombre;
    private javax.swing.JLabel labelModificarPrecio;
    private javax.swing.JLabel labelModificarProveedor;
    private javax.swing.JLabel labelModificarTalle;
    private javax.swing.JLabel labelNuevaDescripcion;
    private javax.swing.JLabel labelNuevoCodigo;
    private javax.swing.JLabel labelNuevoNombre;
    private javax.swing.JLabel labelNuevoPrecio;
    private javax.swing.JLabel labelNuevoProveedor;
    private javax.swing.JLabel labelNuevoTalle;
    private javax.swing.JLabel labelStockMinimo;
    private javax.swing.JLabel labelStockMinimoModificar;
    private javax.swing.JTabbedPane menuProductos;
    private javax.swing.JPanel panelModificarProducto;
    private javax.swing.JPanel panelNuevoProducto;
    private javax.swing.JTable tablaBuscarProductos;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModificarCodigo;
    private javax.swing.JTextField txtModificarDescripcion;
    private javax.swing.JTextField txtModificarNombre;
    private javax.swing.JTextField txtModificarPrecio;
    private javax.swing.JTextField txtNuevaDescripcion;
    private javax.swing.JTextField txtNuevoCodigo;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoPrecio;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtStockMinimoModificar;
    // End of variables declaration//GEN-END:variables
}
