package Interfaz;

import Datos.OperacionesBaseDeDatos;
import Entidades.Cliente;
import javax.swing.JFrame;
import Operaciones.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaABMClientes extends javax.swing.JFrame {
    
    //Usados para llamar a los metodos de dichas clases
    OperacionesBaseDeDatos opBdd = new OperacionesBaseDeDatos();
    OperacionesInterfaz opInterfaz = new OperacionesInterfaz();
    OperacionesClases opClases = new OperacionesClases();
    ValidacionesClases validacionClase = new ValidacionesClases();
    
    //Variable usada para abrir la ventana
    private static VentanaABMClientes ventana=null;
    
    public VentanaABMClientes() {
        initComponents();
        //Evita que se cierre el programa cuando se cierra la ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Evita que se pueda ingresar o cambiar la id en el textfield
        txtID.setEnabled(false);
    }

    //Metodo usado para abrir la ventana. Evita que se abran multiples ventanas del mismo tipo
    public static VentanaABMClientes obtenerVentanaClientes(){
        if (ventana==null) {
            ventana = new VentanaABMClientes();
        }
        return ventana;
    }
    
    //Vacia los textfield en la pestaña Modificar/Baja
    public void vaciarModificar(){
        txtID.setText("");
        txtModificarNombre.setText("");
        txtModificarApellido.setText("");
        txtModificarDNI.setText("");
        txtModificarDireccion.setText("");
        txtModificarEmail.setText("");
        txtModificarTelefono.setText("");
        txtModificarFechaNacimiento.setText("");
    }
    
    //Vacia los textfield en la pestaña Nuevo
    public void vaciarNuevo(){
        txtNuevoNombre.setText("");
        txtNuevoApellido.setText("");
        txtNuevoDNI.setText("");
        txtNuevaDireccion.setText("");
        txtNuevoEmail.setText("");
        txtNuevoTelefono.setText("");
        txtNuevaFechaNacimiento.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuClientes = new javax.swing.JTabbedPane();
        panelNuevoCliente = new javax.swing.JPanel();
        labelNuevoNombre = new javax.swing.JLabel();
        labelNuevoApellido = new javax.swing.JLabel();
        labelNuevoDNI = new javax.swing.JLabel();
        labelNuevaDireccion = new javax.swing.JLabel();
        labelNuevoTelefono = new javax.swing.JLabel();
        labelNuevoEmail = new javax.swing.JLabel();
        labelNuevaFechaNacimiento = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();
        txtNuevoApellido = new javax.swing.JTextField();
        txtNuevoDNI = new javax.swing.JTextField();
        txtNuevaDireccion = new javax.swing.JTextField();
        txtNuevoTelefono = new javax.swing.JTextField();
        txtNuevoEmail = new javax.swing.JTextField();
        txtNuevaFechaNacimiento = new javax.swing.JTextField();
        btnGuardarClienteNuevo = new javax.swing.JButton();
        btnVaciarNuevo = new javax.swing.JButton();
        panelModificarCliente = new javax.swing.JPanel();
        txtModificarApellido = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        txtModificarDireccion = new javax.swing.JTextField();
        btnModificarCliente = new javax.swing.JButton();
        labelModificarNombre = new javax.swing.JLabel();
        comboBuscarCliente = new javax.swing.JComboBox<>();
        txtModificarEmail = new javax.swing.JTextField();
        txtModificarTelefono = new javax.swing.JTextField();
        labelModificarDirecccion = new javax.swing.JLabel();
        labelModificarApellido = new javax.swing.JLabel();
        btnGuardarClienteModificado = new javax.swing.JButton();
        txtModificarFechaNacimiento = new javax.swing.JTextField();
        labelModificarTelefono = new javax.swing.JLabel();
        labelModificarDNI = new javax.swing.JLabel();
        labelModificarEmail = new javax.swing.JLabel();
        labelModificarFechaNacimiento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscarClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        txtModificarNombre = new javax.swing.JTextField();
        txtModificarDNI = new javax.swing.JTextField();
        txtBuscarCliente = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        labelModificarEstado = new javax.swing.JLabel();
        btnVaciarModificacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Clientes");
        setResizable(false);

        menuClientes.setToolTipText("");

        labelNuevoNombre.setText("Nombre");

        labelNuevoApellido.setText("Apellido");

        labelNuevoDNI.setText("DNI");

        labelNuevaDireccion.setText("Direccion");

        labelNuevoTelefono.setText("Telefono");

        labelNuevoEmail.setText("Email");

        labelNuevaFechaNacimiento.setText("Fecha de nacimiento");

        btnGuardarClienteNuevo.setText("Guardar");
        btnGuardarClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteNuevoActionPerformed(evt);
            }
        });

        btnVaciarNuevo.setText("Vaciar campos");
        btnVaciarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoClienteLayout = new javax.swing.GroupLayout(panelNuevoCliente);
        panelNuevoCliente.setLayout(panelNuevoClienteLayout);
        panelNuevoClienteLayout.setHorizontalGroup(
            panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoClienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNuevoApellido)
                    .addComponent(labelNuevoNombre)
                    .addComponent(labelNuevoDNI)
                    .addComponent(labelNuevaDireccion))
                .addGap(25, 25, 25)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtNuevoApellido)
                    .addComponent(txtNuevoDNI)
                    .addComponent(txtNuevaDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoClienteLayout.createSequentialGroup()
                        .addComponent(labelNuevaFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(txtNuevaFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoClienteLayout.createSequentialGroup()
                        .addComponent(labelNuevoEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoClienteLayout.createSequentialGroup()
                        .addComponent(labelNuevoTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVaciarNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarClienteNuevo)
                .addGap(26, 26, 26))
        );
        panelNuevoClienteLayout.setVerticalGroup(
            panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoClienteLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevoNombre)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoTelefono))
                .addGap(26, 26, 26)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoApellido)
                    .addComponent(txtNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoEmail))
                .addGap(31, 31, 31)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevoDNI)
                    .addComponent(txtNuevoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevaFechaNacimiento)
                    .addComponent(txtNuevaFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevaDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(panelNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVaciarNuevo)
                    .addComponent(btnGuardarClienteNuevo))
                .addGap(37, 37, 37))
        );

        menuClientes.addTab("Nuevo", panelNuevoCliente);

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setText("Modificar");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        labelModificarNombre.setText("Nombre");

        comboBuscarCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Apellido" }));

        labelModificarDirecccion.setText("Direccion");

        labelModificarApellido.setText("Apellido");

        btnGuardarClienteModificado.setText("Guardar");
        btnGuardarClienteModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteModificadoActionPerformed(evt);
            }
        });

        labelModificarTelefono.setText("Telefono");

        labelModificarDNI.setText("DNI");

        labelModificarEmail.setText("Email");

        labelModificarFechaNacimiento.setText("Fecha de nacimiento");

        tablaBuscarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "DNI", "Dirección", "Teléfono", "Email", "Fecha de nacimiento", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBuscarClientes);
        if (tablaBuscarClientes.getColumnModel().getColumnCount() > 0) {
            tablaBuscarClientes.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        labelID.setText("ID");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Deshabilitado" }));

        labelModificarEstado.setText("Estado");

        btnVaciarModificacion.setText("Vaciar campos");
        btnVaciarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarModificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarClienteLayout = new javax.swing.GroupLayout(panelModificarCliente);
        panelModificarCliente.setLayout(panelModificarClienteLayout);
        panelModificarClienteLayout.setHorizontalGroup(
            panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarClienteLayout.createSequentialGroup()
                        .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                .addComponent(labelModificarFechaNacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModificarFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelModificarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelModificarEmail)
                                    .addComponent(labelID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                        .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModificarClienteLayout.createSequentialGroup()
                                                .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModificarClienteLayout.createSequentialGroup()
                                                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtModificarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtModificarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                                        .addComponent(labelModificarTelefono)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                                        .addComponent(labelModificarDirecccion)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtModificarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                                .addComponent(labelModificarEstado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnVaciarModificacion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGuardarClienteModificado)))))))
                        .addGap(18, 18, 18))
                    .addGroup(panelModificarClienteLayout.createSequentialGroup()
                        .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificarCliente)
                                    .addGroup(panelModificarClienteLayout.createSequentialGroup()
                                        .addComponent(comboBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarCliente)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelModificarClienteLayout.setVerticalGroup(
            panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(comboBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarCliente)
                .addGap(12, 12, 12)
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelModificarEstado)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelModificarApellido)
                        .addComponent(txtModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModificarDNI)
                    .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModificarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelModificarDirecccion)
                        .addComponent(txtModificarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificarTelefono)
                    .addComponent(txtModificarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificarEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModificarFechaNacimiento)
                    .addComponent(txtModificarFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarClienteModificado)
                    .addComponent(btnVaciarModificacion))
                .addGap(43, 43, 43))
        );

        menuClientes.addTab("Modificar / Baja", panelModificarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuClientes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //Boton que busca los clientes en la base de datos que cumplan con los terminos
    //de busqueda y los agrega a la tabla de clientes
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
    opInterfaz.llenarTabla(opBdd.buscarCliente(txtBuscarCliente.getText(),
            comboBuscarCliente.getSelectedItem().toString().toLowerCase()), tablaBuscarClientes);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    //Boton que carga los campos textfield con los datos del cliente seleccionado en la tabla
    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        if (tablaBuscarClientes.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono ningún cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            opInterfaz.llenarCamposCliente(tablaBuscarClientes, txtID, txtModificarNombre, txtModificarApellido,
                    txtModificarDNI, txtModificarDireccion, txtModificarTelefono, txtModificarEmail, txtModificarFechaNacimiento, comboEstado);
        }
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    //Boton que guarda el cliente modificado en la base de datos
    private void btnGuardarClienteModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteModificadoActionPerformed
        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Cliente cliente = opClases.crearCliente(txtModificarNombre.getText(), txtModificarApellido.getText(), txtModificarDireccion.getText(), txtModificarDNI.getText(),
                    txtModificarTelefono.getText(), txtModificarEmail.getText(), txtModificarFechaNacimiento.getText());  
            if (validacionClase.ValidarCliente(cliente)) {
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Actualizar cliente?", "Confirmar", JOptionPane.YES_NO_OPTION); 
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (opBdd.guardarClienteModificado(cliente, comboEstado.getSelectedItem().toString(), txtID.getText())) {
                        JOptionPane.showMessageDialog(null, "El DNI del cliente ya existe. Seleccione otro.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Datos actualizados");
                        vaciarModificar();
                    }
                } 
            }
        }
    }//GEN-LAST:event_btnGuardarClienteModificadoActionPerformed

    //Boton que vacia los campos de los textfield en la pestaña Modificar/Baja
    private void btnVaciarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarModificacionActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea vaciar los campos?", "Confirmar", JOptionPane.YES_NO_OPTION); 
        if (eleccion == JOptionPane.YES_OPTION) {
            vaciarModificar();
        } 
    }//GEN-LAST:event_btnVaciarModificacionActionPerformed

    //Boton que vacia los campos de los textfield en la pestaña Nuevo
    private void btnVaciarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarNuevoActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea vaciar los campos?", "Confirmar", JOptionPane.YES_NO_OPTION); 
        if (eleccion == JOptionPane.YES_OPTION) {
            vaciarNuevo();
        } 
    }//GEN-LAST:event_btnVaciarNuevoActionPerformed

    //Boton que guarda el cliente nuevo en la base de datos
    private void btnGuardarClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteNuevoActionPerformed
        if (txtNuevoNombre.getText().equals("") || txtNuevoApellido.getText().equals("") || txtNuevoDNI.getText().equals("") || txtNuevaDireccion.getText().equals("") 
                || txtNuevoTelefono.getText().equals("") || txtNuevoEmail.getText().equals("") || txtNuevaFechaNacimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Cliente cliente = opClases.crearCliente(txtNuevoNombre.getText(), txtNuevoApellido.getText(), txtNuevaDireccion.getText(), txtNuevoDNI.getText(),
                    txtNuevoTelefono.getText(), txtNuevoEmail.getText(), txtNuevaFechaNacimiento.getText());  
            if (validacionClase.ValidarCliente(cliente)) {
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Guardar cliente?", "Confirmar", JOptionPane.YES_NO_OPTION); 
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (opBdd.guardarClienteNuevo(cliente)) {
                        JOptionPane.showMessageDialog(null, "El DNI del cliente ya existe. Seleccione otro.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Datos guardados");
                        vaciarNuevo();
                    }
                } 
            }
        }
    }//GEN-LAST:event_btnGuardarClienteNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaABMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaABMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaABMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaABMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaABMClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnGuardarClienteModificado;
    private javax.swing.JButton btnGuardarClienteNuevo;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnVaciarModificacion;
    private javax.swing.JButton btnVaciarNuevo;
    private javax.swing.JComboBox<String> comboBuscarCliente;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelModificarApellido;
    private javax.swing.JLabel labelModificarDNI;
    private javax.swing.JLabel labelModificarDirecccion;
    private javax.swing.JLabel labelModificarEmail;
    private javax.swing.JLabel labelModificarEstado;
    private javax.swing.JLabel labelModificarFechaNacimiento;
    private javax.swing.JLabel labelModificarNombre;
    private javax.swing.JLabel labelModificarTelefono;
    private javax.swing.JLabel labelNuevaDireccion;
    private javax.swing.JLabel labelNuevaFechaNacimiento;
    private javax.swing.JLabel labelNuevoApellido;
    private javax.swing.JLabel labelNuevoDNI;
    private javax.swing.JLabel labelNuevoEmail;
    private javax.swing.JLabel labelNuevoNombre;
    private javax.swing.JLabel labelNuevoTelefono;
    private javax.swing.JTabbedPane menuClientes;
    private javax.swing.JPanel panelModificarCliente;
    private javax.swing.JPanel panelNuevoCliente;
    private javax.swing.JTable tablaBuscarClientes;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModificarApellido;
    private javax.swing.JTextField txtModificarDNI;
    private javax.swing.JTextField txtModificarDireccion;
    private javax.swing.JTextField txtModificarEmail;
    private javax.swing.JTextField txtModificarFechaNacimiento;
    private javax.swing.JTextField txtModificarNombre;
    private javax.swing.JTextField txtModificarTelefono;
    private javax.swing.JTextField txtNuevaDireccion;
    private javax.swing.JTextField txtNuevaFechaNacimiento;
    private javax.swing.JTextField txtNuevoApellido;
    private javax.swing.JTextField txtNuevoDNI;
    private javax.swing.JTextField txtNuevoEmail;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoTelefono;
    // End of variables declaration//GEN-END:variables
}
