package Interfaz;

import Datos.OperacionesBaseDeDatos;
import Entidades.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Operaciones.*;

/**
 *
 * @author User
 */
public class VentanaABMUsuarios extends javax.swing.JFrame {

    //Usados para llamar a los metodos de dichas clases
    OperacionesBaseDeDatos opBdd = new OperacionesBaseDeDatos();
    OperacionesInterfaz opInterfaz = new OperacionesInterfaz();
    OperacionesClases opClases = new OperacionesClases();
    ValidacionesClases validacionClase = new ValidacionesClases();
    
    //Variable usada para abrir la ventana
    private static VentanaABMUsuarios ventana=null;
    
    public VentanaABMUsuarios() {
        initComponents();
        //Evita que se cierre el programa cuando se cierra la ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Evita que se pueda ingresar o cambiar la id en el textfield
        txtID.setEnabled(false);
    }

    //Metodo usado para abrir la ventana. Evita que se abran multiples ventanas del mismo tipo
    public static VentanaABMUsuarios obtenerVentanaUsuarios(){
        if (ventana==null) {
            ventana = new VentanaABMUsuarios();
        }
        return ventana;
    }
    
    //Vacia los textfield en la pestaña Modificar/Baja
    public void vaciarModificar(){
        txtModificarNombre.setText("");
        txtModificarApellido.setText("");
        txtModificarUsuario.setText("");
        txtModificarContrasenia.setText("");
        txtModificarEmail.setText("");
        txtID.setText("");
    }
    
    //Vacia los textfield en la pestaña Nuevo
    public void vaciarNuevo(){
        txtNuevoNombre.setText("");
        txtNuevoApellido.setText("");
        txtNuevoUsuario.setText("");
        txtNuevaContrasenia.setText("");
        txtNuevoEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuUsuarios = new javax.swing.JTabbedPane();
        panelNuevoUsuario = new javax.swing.JPanel();
        labelNuevoNombre = new javax.swing.JLabel();
        labelNuevoApellido = new javax.swing.JLabel();
        labelNuevoEmail = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();
        txtNuevoApellido = new javax.swing.JTextField();
        txtNuevoEmail = new javax.swing.JTextField();
        btnGuardarUsuarioNuevo = new javax.swing.JButton();
        btnVaciarNuevo = new javax.swing.JButton();
        labelNuevoUsuario = new javax.swing.JLabel();
        labelNuevaContrasenia = new javax.swing.JLabel();
        txtNuevoUsuario = new javax.swing.JTextField();
        txtNuevaContrasenia = new javax.swing.JPasswordField();
        panelModificarUsuario = new javax.swing.JPanel();
        btnBuscarUsuario = new javax.swing.JButton();
        txtModificarApellido = new javax.swing.JTextField();
        btnModificarUsuario = new javax.swing.JButton();
        labelModificarNombre = new javax.swing.JLabel();
        txtModificarEmail = new javax.swing.JTextField();
        labelModificarApellido = new javax.swing.JLabel();
        btnGuardarUsuarioModificado = new javax.swing.JButton();
        labelModificarEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscarUsuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        txtModificarNombre = new javax.swing.JTextField();
        txtBuscarUsuario = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        labelModificarEstado = new javax.swing.JLabel();
        btnVaciarModificacion = new javax.swing.JButton();
        labelBuscarNombre = new javax.swing.JLabel();
        labelModificarUsuario = new javax.swing.JLabel();
        labelModificarContrasenia = new javax.swing.JLabel();
        txtModificarUsuario = new javax.swing.JTextField();
        txtModificarContrasenia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Usuarios");
        setResizable(false);

        labelNuevoNombre.setText("Nombre");

        labelNuevoApellido.setText("Apellido");

        labelNuevoEmail.setText("Email");

        btnGuardarUsuarioNuevo.setText("Guardar");
        btnGuardarUsuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioNuevoActionPerformed(evt);
            }
        });

        btnVaciarNuevo.setText("Vaciar campos");
        btnVaciarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarNuevoActionPerformed(evt);
            }
        });

        labelNuevoUsuario.setText("Usuario");

        labelNuevaContrasenia.setText("Contraseña");

        javax.swing.GroupLayout panelNuevoUsuarioLayout = new javax.swing.GroupLayout(panelNuevoUsuario);
        panelNuevoUsuario.setLayout(panelNuevoUsuarioLayout);
        panelNuevoUsuarioLayout.setHorizontalGroup(
            panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoUsuarioLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVaciarNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarUsuarioNuevo)
                        .addGap(32, 32, 32))
                    .addGroup(panelNuevoUsuarioLayout.createSequentialGroup()
                        .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNuevoNombre)
                            .addComponent(labelNuevoApellido)
                            .addComponent(labelNuevoEmail))
                        .addGap(18, 18, 18)
                        .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelNuevoUsuarioLayout.createSequentialGroup()
                                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelNuevoUsuarioLayout.createSequentialGroup()
                                        .addComponent(txtNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNuevaContrasenia))
                                    .addGroup(panelNuevoUsuarioLayout.createSequentialGroup()
                                        .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNuevoUsuario)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNuevaContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(186, 208, Short.MAX_VALUE))))
        );
        panelNuevoUsuarioLayout.setVerticalGroup(
            panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoUsuarioLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevoNombre)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoUsuario))
                .addGap(26, 26, 26)
                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoApellido)
                    .addComponent(labelNuevaContrasenia)
                    .addComponent(txtNuevaContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNuevoEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(panelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUsuarioNuevo)
                    .addComponent(btnVaciarNuevo))
                .addGap(21, 21, 21))
        );

        menuUsuarios.addTab("Nuevo", panelNuevoUsuario);

        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        btnModificarUsuario.setText("Modificar");
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });

        labelModificarNombre.setText("Nombre");

        labelModificarApellido.setText("Apellido");

        btnGuardarUsuarioModificado.setText("Guardar");
        btnGuardarUsuarioModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioModificadoActionPerformed(evt);
            }
        });

        labelModificarEmail.setText("Email");

        tablaBuscarUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Usuario", "Contraseña", "Email", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBuscarUsuarios);

        labelID.setText("ID");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Deshabilitado" }));

        labelModificarEstado.setText("Estado");

        btnVaciarModificacion.setText("Vaciar campos");
        btnVaciarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarModificacionActionPerformed(evt);
            }
        });

        labelBuscarNombre.setText("Nombre");

        labelModificarUsuario.setText("Usuario");

        labelModificarContrasenia.setText("Contraseña");

        javax.swing.GroupLayout panelModificarUsuarioLayout = new javax.swing.GroupLayout(panelModificarUsuario);
        panelModificarUsuario.setLayout(panelModificarUsuarioLayout);
        panelModificarUsuarioLayout.setHorizontalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVaciarModificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarUsuarioModificado)
                        .addGap(29, 29, 29))
                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarUsuario)
                            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(labelBuscarNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarUsuario))
                            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelID)
                                    .addComponent(labelModificarApellido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelModificarContrasenia)
                                            .addComponent(labelModificarUsuario))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                                                .addComponent(txtModificarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelModificarEstado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                                                .addComponent(txtModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelModificarEmail)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtModificarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        panelModificarUsuarioLayout.setVerticalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(labelBuscarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarUsuario)
                .addGap(12, 12, 12)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificarUsuario)
                    .addComponent(txtModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificarEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModificarContrasenia)
                    .addComponent(txtModificarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificarEstado)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModificarApellido))
                .addGap(66, 66, 66)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUsuarioModificado)
                    .addComponent(btnVaciarModificacion))
                .addGap(45, 45, 45))
        );

        menuUsuarios.addTab("Modificar / Baja", panelModificarUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Boton que guarda el usuario nuevo en la base de datos
    private void btnGuardarUsuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioNuevoActionPerformed
        if (txtNuevoNombre.getText().equals("") || txtNuevoApellido.getText().equals("") || txtNuevoUsuario.getText().equals("") 
                || txtNuevaContrasenia.getText().equals("") || txtNuevoEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Usuario user = opClases.crearUsuario(txtNuevoNombre.getText(), txtNuevoApellido.getText(), txtNuevoUsuario.getText(), txtNuevaContrasenia.getText(), txtNuevoEmail.getText());
            if (validacionClase.ValidarUsuario(user)) {
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Guardar usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (opBdd.guardarUsuarioNuevo(user)) {
                        JOptionPane.showMessageDialog(null, "El nombre de cuenta del usuario ya existe. Seleccione otro.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Datos guardados");
                        vaciarNuevo();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarUsuarioNuevoActionPerformed

    //Boton que vacia los campos de los textfield en la pestaña Nuevo
    private void btnVaciarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarNuevoActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea vaciar los campos?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (eleccion == JOptionPane.YES_OPTION) {
            vaciarNuevo();
        }
    }//GEN-LAST:event_btnVaciarNuevoActionPerformed

    //Boton que busca los usuarios en la base de datos que cumplan con los terminos
    //de busqueda y los agrega a la tabla de usuarios
    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        opInterfaz.llenarTabla(opBdd.buscarUsuario(txtBuscarUsuario.getText()), tablaBuscarUsuarios);
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    //Boton que carga los campos textfield con los datos del usuario seleccionado en la tabla
    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        if (tablaBuscarUsuarios.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono ningún usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            opInterfaz.llenarCamposUsuario(tablaBuscarUsuarios, txtID, txtModificarNombre, txtModificarApellido, txtModificarUsuario, txtModificarContrasenia, txtModificarEmail, comboEstado);
        }
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    //Boton que guarda el usuario modificado en la base de datos
    private void btnGuardarUsuarioModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioModificadoActionPerformed
        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Usuario user = opClases.crearUsuario(txtModificarNombre.getText(), txtModificarApellido.getText(), txtModificarUsuario.getText(), txtModificarContrasenia.getText(), txtModificarEmail.getText());
            if (validacionClase.ValidarUsuario(user)) {
                int eleccion = JOptionPane.showConfirmDialog(null, "¿Actualizar usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (eleccion == JOptionPane.YES_OPTION) {
                    if (opBdd.guardarUsuarioModificado(user, comboEstado.getSelectedItem().toString(), txtID.getText())) {
                        JOptionPane.showMessageDialog(null, "Este usuario ya existe. Seleccione otro nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Datos actualizados");
                        vaciarModificar();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarUsuarioModificadoActionPerformed

    //Boton que vacia los campos de los textfield en la pestaña Modificar/Baja
    private void btnVaciarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarModificacionActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea vaciar los campos?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (eleccion == JOptionPane.YES_OPTION) {
            vaciarModificar();
        }
    }//GEN-LAST:event_btnVaciarModificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaABMUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaABMUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaABMUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaABMUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaABMUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnGuardarUsuarioModificado;
    private javax.swing.JButton btnGuardarUsuarioNuevo;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnVaciarModificacion;
    private javax.swing.JButton btnVaciarNuevo;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscarNombre;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelModificarApellido;
    private javax.swing.JLabel labelModificarContrasenia;
    private javax.swing.JLabel labelModificarEmail;
    private javax.swing.JLabel labelModificarEstado;
    private javax.swing.JLabel labelModificarNombre;
    private javax.swing.JLabel labelModificarUsuario;
    private javax.swing.JLabel labelNuevaContrasenia;
    private javax.swing.JLabel labelNuevoApellido;
    private javax.swing.JLabel labelNuevoEmail;
    private javax.swing.JLabel labelNuevoNombre;
    private javax.swing.JLabel labelNuevoUsuario;
    private javax.swing.JTabbedPane menuUsuarios;
    private javax.swing.JPanel panelModificarUsuario;
    private javax.swing.JPanel panelNuevoUsuario;
    private javax.swing.JTable tablaBuscarUsuarios;
    private javax.swing.JTextField txtBuscarUsuario;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModificarApellido;
    private javax.swing.JTextField txtModificarContrasenia;
    private javax.swing.JTextField txtModificarEmail;
    private javax.swing.JTextField txtModificarNombre;
    private javax.swing.JTextField txtModificarUsuario;
    private javax.swing.JPasswordField txtNuevaContrasenia;
    private javax.swing.JTextField txtNuevoApellido;
    private javax.swing.JTextField txtNuevoEmail;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
