package Interfaz;

import Datos.OperacionesBaseDeDatos;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Operaciones.*;
/**
 *
 * @author User
 */
public class VentanaRegistroDeVentas extends javax.swing.JFrame {
    
    //Usados para llamar a los metodos de dichas clases
    OperacionesBaseDeDatos opBdd = new OperacionesBaseDeDatos();
    OperacionesInterfaz opInterfaz = new OperacionesInterfaz();
    Logica log = new Logica();
    
    //Variable usada para abrir la ventana
    private static VentanaRegistroDeVentas ventana=null;
    
    
    public VentanaRegistroDeVentas() {
        initComponents();
        //Evita que se cierre el programa cuando se cierra la ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    //Metodo usado para abrir la ventana. Evita que se abran multiples ventanas del mismo tipo
    public static VentanaRegistroDeVentas obtenerVentanaRegistroDeVentas(){
        if (ventana==null) {
            ventana = new VentanaRegistroDeVentas();
        }
        return ventana;
    }
    
    //Devuelve la fecha ingresada en el JDateChooser
    public String obtenerFechaIngresada(){
        String fecha="";
        Date f = dateFecha.getDate();
        if (f!=null) {
            DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            fecha = formatoFecha.format(f);
        }
        return fecha;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroVentas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        btnBuscarRegistroVenta = new javax.swing.JButton();
        txtBuscarRegistroVenta = new javax.swing.JTextField();
        comboBuscarRegistroVenta = new javax.swing.JComboBox<>();
        btnCargarProductosVendidos = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaBuscarRegistroVenta = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        btnImprimir = new javax.swing.JButton();
        dateFecha = new com.toedter.calendar.JDateChooser();
        btnBuscarRegistroFecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de ventas");
        setResizable(false);

        panelRegistroVentas.setToolTipText("");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaVentas);

        btnBuscarRegistroVenta.setText("Buscar");
        btnBuscarRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRegistroVentaActionPerformed(evt);
            }
        });

        comboBuscarRegistroVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Vendedor" }));

        btnCargarProductosVendidos.setText("Cargar");
        btnCargarProductosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProductosVendidosActionPerformed(evt);
            }
        });

        tablaBuscarRegistroVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "ID Cliente", "Nombre Cliente", "Vendedor", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaBuscarRegistroVenta);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnBuscarRegistroFecha.setText("Buscar");
        btnBuscarRegistroFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRegistroFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroVentasLayout = new javax.swing.GroupLayout(panelRegistroVentas);
        panelRegistroVentas.setLayout(panelRegistroVentasLayout);
        panelRegistroVentasLayout.setHorizontalGroup(
            panelRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addGroup(panelRegistroVentasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImprimir))
                    .addGroup(panelRegistroVentasLayout.createSequentialGroup()
                        .addGroup(panelRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargarProductosVendidos)
                            .addGroup(panelRegistroVentasLayout.createSequentialGroup()
                                .addComponent(comboBuscarRegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarRegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRegistroVenta)
                                .addGap(35, 35, 35)
                                .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRegistroFecha)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRegistroVentasLayout.setVerticalGroup(
            panelRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroVentasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBuscarRegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscarRegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarRegistroVenta))
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRegistroFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarProductosVendidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistroVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistroVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Boton que busca los registros de ventas en la base de datos que cumplan con los terminos
    //de busqueda y los agrega a la tabla de registros de ventas
    private void btnBuscarRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRegistroVentaActionPerformed
        opInterfaz.llenarTabla(opBdd.buscarRegistroVentas(txtBuscarRegistroVenta.getText(),
            comboBuscarRegistroVenta.getSelectedItem().toString().toLowerCase()), tablaBuscarRegistroVenta);
    }//GEN-LAST:event_btnBuscarRegistroVentaActionPerformed

    //Carga en la tabla los productos vendidos en la venta seleccionada
    private void btnCargarProductosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProductosVendidosActionPerformed
        if (tablaBuscarRegistroVenta.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna venta", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            opInterfaz.llenarTabla(opBdd.obtenerProductosVendidos(Integer.parseInt(tablaBuscarRegistroVenta.getValueAt(tablaBuscarRegistroVenta.getSelectedRow(), 0).toString())), tablaVentas);
        }
    }//GEN-LAST:event_btnCargarProductosVendidosActionPerformed

    //Genera la factura de la venta seleccionada
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if (tablaVentas.getRowCount()==0) {
            JOptionPane.showMessageDialog(null, "No hay elementos para imprimir.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int eleccion = JOptionPane.showConfirmDialog(null, "¿Generar factura?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (eleccion == JOptionPane.YES_OPTION) {
                log.imprimirRegistro(tablaVentas, tablaBuscarRegistroVenta);
            }
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    //Boton que busca los registros de ventas en la base de datos en base a la fecha
    //ingresada y los agrega a la tabla de registros de ventas
    private void btnBuscarRegistroFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRegistroFechaActionPerformed
        opInterfaz.llenarTabla(opBdd.buscarRegistroVentasPorFecha(obtenerFechaIngresada()), tablaBuscarRegistroVenta); 
    }//GEN-LAST:event_btnBuscarRegistroFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroDeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRegistroFecha;
    private javax.swing.JButton btnBuscarRegistroVenta;
    private javax.swing.JButton btnCargarProductosVendidos;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> comboBuscarRegistroVenta;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelRegistroVentas;
    private javax.swing.JTable tablaBuscarRegistroVenta;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtBuscarRegistroVenta;
    // End of variables declaration//GEN-END:variables
}
